version: "3"
services:
  fake-rdbms:
    container_name: fake-rdbms
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3066:3066
    volumes: 
      - fake_rdbms_volume:/app/data
    command: [ "npm", "t" ]
volumes:
  fake_rdbms_volume:
    driver: local
    driver_opts:
      type: none
      device: /data
      o: bind
